ls_name_value: more work
Handle filenames containing spaces and other strange
characters. Add --all option to include hidden files
(i.e. those starting with '.') similar to the filenames
output by the 'ls -A' command. Add --empty option to
replace an empty value with the string: '<empty>'.



git-svn-id: https://svn.bingwo.ca/repos/lsscsi/trunk@188 aaa919c1-9816-4d37-901d-0171dbb97e96

diff --git a/scripts/ls_name_value b/scripts/ls_name_value
--- a/scripts/ls_name_value
+++ b/scripts/ls_name_value
@@ -7,28 +7,32 @@
 # followed by their ASCII contents (i.e. their values) as appropriate.
 # It targets sysfs (/sys ) in Linux but may be useful in other contexts.
 
-version_str="1.05 20230526"
+version_str="1.08 20230527"
 
+all=0
 dir=0
-show=0
-is_root=0     # 0 for true; 1 for false (sorry C)
+empty=0
 nosym=0
 otherfs=0
+show=0
+is_root=0     # 0 for true; 1 for false (sorry C)
 first_st_dev=0
 verbose=0
 
 # The following are for the getopt(1) command from util-linux which
 # follows the function definitions, about 100 lines down.
 script_name=$(basename "$0")
-short=dhNosvV
-long=dir,help,nosym,otherfs,show,verbose,version
+short="adehNosvV"
+long="all,dir,empty,help,nosym,otherfs,show,verbose,version"
 
 
 usage()
 {
-  echo "Usage: ls_name_value [-d] [-h] [-N] [-o] [-s] [-v] [-V] [<name>*]"
-  echo "  where:  -d, --dir         descend if <name> is directory"
+  echo "Usage: ls_name_value [-a] [-d] [-e] [-h] [-N] [-o] [-s] [-v] [-V] [<name>*]"
+  echo "  where:  -a, --all         include hidden filename (start with '.')"
+  echo "          -d, --dir         descend if <name> is directory"
   echo "                            descends 1 level; -dd descends 2 levels"
+  echo "          -e, --empty       output <value> as '<empty>' rather than blank"
   echo "          -h, --help        print usage message"
   echo "          -N, --nosym       do not descend symlinks to directories"
   echo "          -o, --otherfs     not descending to other fs is default, override"
@@ -45,7 +49,7 @@ get_root_perm()
 {
   local s
 
-  s=$(stat -c '%a' "$1") 
+  s=$(stat -c '%a' "$1")
   if [ -n "$s" ] ; then
     echo "${s:0:1}"
   else
@@ -68,9 +72,14 @@ one_name_value()
   fi
 
   if [ -f "${1}" ] ; then
-    if [ ${is_root} -eq 1 ] ; then    # false, so non-root
+    if [ ${is_root} -ne 0 ] ; then    # false, so non-root
       if [ -r "${1}" ] ; then
-        value=$( head -c 256 "${1}" 2> /dev/null | tr -d '\0' | tr '\n' " " )
+        value=$( head -c 256 "${1}" 2> /dev/null | tr -d '\0' )
+        if [ $empty -eq 0 ] || [ -n "${value}" ] ; then
+          value=$( echo  "${value}" | tr '\n' " " )
+        else
+          value="<empty>"
+        fi
         if [ "${1:0:1}" = "/" ] || [ "${1:0:1}" = "." ] ; then
           echo -n "${pad}$( basename "$1" ) : "
         else
@@ -86,10 +95,15 @@ one_name_value()
       else
         echo "${pad}${1} : <cannot access>"
       fi
-    else
+    else        # run by root
       grp=$( get_root_perm "${1}" )
       if [ "${grp}" -ge 4 ] ; then
-        value=$( head -c 256 "${1}" 2> /dev/null | tr -d '\0' | tr '\n' " " )
+        value=$( head -c 256 "${1}" 2> /dev/null | tr -d '\0' )
+        if [ $empty -eq 0 ] || [ -n "${value}" ] ; then
+          value=$( echo  "${value}" | tr '\n' " " )
+        else
+          value="<empty>"
+        fi
         if [ "${1:0:1}" = "/" ] || [ "${1:0:1}" = "." ] ; then
           echo -n "${pad}$( basename "$1" ) : "
         else
@@ -134,9 +148,9 @@ if (( EUID != 0 )); then
 fi
 
 # Reference: /usr/share/doc/util-linux/examples/getopt-example.bash
-TEMP=$(getopt -o $short --long $long --name "$script_name" -- "$@")
+if ! TEMP=$(getopt -o $short --long $long --name "$script_name" -- "$@") ; then
 
-if [ $? -ne 0 ]; then
+# if [ $? -ne 0 ]; then
   echo 'Terminating...' >&2
   exit 1
 fi
@@ -145,7 +159,9 @@ eval set -- "${TEMP}"
 
 while :; do
   case "${1}" in
+    -a | --all        ) (( all=all+1 )) ;          shift 1 ;;
     -d | --dir        ) (( dir=dir+1 )) ;          shift 1 ;;
+    -e | --empty      ) (( empty=empty+1 )) ;      shift 1 ;;
     -h | --help       ) usage;                     exit 0 ;;
     -N | --nosym      ) (( nosym=nosym+1 )) ;      shift 1 ;;
     -o | --otherfs    ) (( otherfs=otherfs+1 )) ;  shift 1 ;;
@@ -156,29 +172,6 @@ while :; do
     *                 ) echo "Error parsing $1";   exit 1 ;;
   esac
 done
-
-# The following code with leading "##"s is the previous way of handling
-# command line options (i.e. prior to using getopt(1) ).
-## opt="$1"
-## while test ! -z "$opt" -a -z "${opt##-*}"; do
-##   opt=${opt#-}
-##   case "$opt" in
-##     d|-dir) let dir=$dir+1 ;;
-##     dd) let dir=$dir+2 ;;
-##     ddd) let dir=$dir+2 ;;
-##     h|-help) usage ; exit 0 ;;
-##     N|-nosym) let nosym=$nosym+1 ;;
-##     o|-otherfs) let otherfs=$otherfs+1 ;;
-##     s|-show) let show=$show+1 ;;
-##     v|-verbose) verbose_arg="-v" ; let verbose=$verbose+1 ;;
-##     vv) verbose_arg="-vv" ; let verbose=$verbose+2 ;;
-##     vvv) verbose_arg="-vvv" ; let verbose=$verbose+3 ;;
-##     V|-version) echo ${version_str} ; exit 0 ;;
-##     *) echo "Unknown option: -$opt " ; exit 1 ;;
-##   esac
-##   shift
-##   opt="$1"
-## done
 
 # If one arguent given and it's a directory, cd to it and swallow
 if [ $# -eq 1 ] && [ -d "$1" ] && [ -x "$1" ] ; then
@@ -200,17 +193,39 @@ if [ $verbose -gt 0 ] ; then
   echo ""
 fi
 
+SAVEIFS=$IFS
+IFS=$'\n'
+
+
+n=$#
 if [ $# -gt 0 ] ; then
-  FILES=$*
+  # place command line arguments into a bash array
+  for (( k=0 ; k<n ; k=k+1 )) ; do
+    fileArray[k]="$1"
+    shift
+  done
 else
-  FILES=$( ls )
+  # place filenames in current directory into a bash array
+  if [ $all -gt 0 ] ; then
+    shopt -s dotglob
+  fi
+  # "shellcheck" says to use mapfile instead of following structure
+  fileArray=($( echo -n "*" ))
+  if [ $all -gt 0 ] ; then
+    shopt -u dotglob
+  fi
 fi
 
-for file in ${FILES}; do
-  if [ "${first_st_dev}" -eq 0 ] ; then
-      first_st_dev=$( stat -c %d "${file}" )
+tLen=${#fileArray[@]}
+for (( k=0; k<tLen; k++ )) ; do
+  name1="${fileArray[$k]}"
+  if [ $verbose -gt 3 ] ; then
+    echo ">> fileArray[$k]: ${name1}"
   fi
-  if [ -h "${file}" ] ; then
+  if [ "${first_st_dev}" -eq 0 ] ; then
+      first_st_dev=$( stat -c %d "${name1}" )
+  fi
+  if [ -h "${name1}" ] ; then
     symlnk1=0
     [ ${nosym} -gt 0 ]
     nosym_active1=$?
@@ -218,26 +233,36 @@ for file in ${FILES}; do
     symlnk1=1
     nosym_active1=1
   fi
-  if [ ${dir} -gt 0 ] && [ -d "${file}" ] && [ -x "${file}" ] && [ ${nosym_active1} -ne 0 ] ; then
+  if [ ${dir} -gt 0 ] && [ -d "${name1}" ] && [ -x "${name1}" ] && [ ${nosym_active1} -ne 0 ] ; then
     if [ ${otherfs} -eq 0 ] ; then
-      a_st_dev=$( stat -c %d "${file}" )
+      a_st_dev=$( stat -c %d "${name1}" )
     else
       a_st_dev=${first_st_dev}
     fi
     if [ "${first_st_dev}" -eq "${a_st_dev}" ] ; then
-      echo ">> descend to: ${file}/:"
+      echo ">> descend to: ${name1}/:"
       cur=$( pwd )
-      if ! cd "${file}" ; then
-        echo "cd to ${file} failed from $( pwd -P) "
+      if ! cd "${name1}" ; then
+        echo "cd to ${name1} failed from $( pwd -P) "
+        IFS=$SAVEIFS
         exit 1
       fi
       if [ ${verbose} -gt 2 ] && [ ${symlnk1} -eq 0 ] ; then
         echo -n "  > physical working directory: "
         pwd -P
       fi
-      FI2=$( ls )
-      for fi2 in ${FI2}; do
-        if [ -h "${fi2}" ] ; then
+      # place filenames in current directory into a bash array
+      if [ $all -gt 0 ] ; then
+        shopt -s dotglob
+      fi
+      fileArray2=($( echo -n "*" ))
+      if [ $all -gt 0 ] ; then
+        shopt -u dotglob
+      fi
+      t2Len=${#fileArray2[@]}
+      for (( j=0; j<t2Len; j++ )) ; do
+        name2="${fileArray2[$j]}"
+        if [ -h "${name2}" ] ; then
           symlnk2=0
           [ ${nosym} -gt 0 ]
           nosym_active2=$?
@@ -245,50 +270,61 @@ for file in ${FILES}; do
           symlnk2=1
           nosym_active2=1
         fi
-        [ ${nosym} -gt 0 ] && [ -h "${fi2}" ]
+        [ ${nosym} -gt 0 ] && [ -h "${name2}" ]
         nosym_active2=$?
-        if [ ${dir} -gt 1 ] && [ -d "${fi2}" ] && [ -x "${fi2}" ] && [ ${nosym_active2} -ne 0 ] ; then
+        if [ ${dir} -gt 1 ] && [ -d "${name2}" ] && [ -x "${name2}" ] && [ ${nosym_active2} -ne 0 ] ; then
           if [ ${otherfs} -eq 0 ] ; then
-            b_st_dev=$( stat -c %d "${fi2}" )
+            b_st_dev=$( stat -c %d "${name2}" )
           else
             b_st_dev=${first_st_dev}
           fi
           if [ "${first_st_dev}" -eq "${b_st_dev}" ] ; then
-            echo "    >> descend to: ${fi2}/:"
+            echo "    >> descend to: ${name2}/:"
             cur2=$( pwd )
-            if ! cd "${fi2}" ; then
-              echo "cd to ${fi2} failed from $( pwd -P) "
+            if ! cd "${name2}" ; then
+              echo "cd to ${name2} failed from $( pwd -P) "
+              IFS=$SAVEIFS
               exit 1
             fi
             if [ ${verbose} -gt 2 ] && [ ${symlnk2} -eq 0 ] ; then
               echo -n "      > physical working directory: "
               pwd -P
             fi
-            FI3=$( ls )
-            for fi3 in ${FI3}; do
-              one_name_value "${fi3}" "        "
+            if [ $all -gt 0 ] ; then
+              shopt -s dotglob
+            fi
+            fileArray3=($( echo -n "*" ))
+            if [ $all -gt 0 ] ; then
+              shopt -u dotglob
+            fi
+            t3Len=${#fileArray3[@]}
+            for (( m=0; m<t3Len; m++ )) ; do
+              one_name_value "${fileArray3[m]}" "        "
             done
             if ! cd "${cur2}" ; then
               echo "cd to ${cur2} failed from $( pwd -P) "
+              IFS=$SAVEIFS
               exit 1
             fi
             echo ""
           else
-            echo "    >> not descending to: ${fi2}/: <different filesystem>"
+            echo "    >> not descending to: ${name2}/: <different filesystem>"
           fi
         else
-          one_name_value "${fi2}" "    "
+          one_name_value "${name2}" "    "
         fi
       done
       if ! cd "${cur}" ; then
         echo "cd to ${cur} failed from $( pwd -P) "
+        IFS=$SAVEIFS
         exit 1
       fi
       echo ""
     else
-      echo ">> not descending to: ${file}/: <different filesystem>"
+      echo ">> not descending to: ${name1}/: <different filesystem>"
     fi
   else
-    one_name_value "${file}"
+    one_name_value "${name1}"
   fi
 done
+IFS=$SAVEIFS
